name: Main build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    - name: Setup Multiplatform build
      run: docker buildx create --name multiplatform --driver docker-container
    - name: Docker login
      run: docker login ghcr.io -u drsylent -p ${{ github.token }}
    - name: Build and push the Docker image
      run: docker build -t ghcr.io/drsylent/cubix/webinar/db:latest --builder multiplatform --platform linux/amd64,linux/arm64 --push .
